### ISSUE TITLE
Need a Designated Officer procurement guide

### ISSUE THREAD

**Issue by bob-fontana** [GSA/ficam-guides#4]
We need a playbook to help the Designated Officer to PIV-enable his/her facility.

**Comment by bob-fontana** [comment]
It appears that 5_Step-5 covers most of the material that I had written so far, but now we want to get into procurement.  Should that be included in this particular repo?   It sure seems that way.  If so, do we make a 5_Step-5A to try to keep things sorted?

Side note: The PACS items on GSA Advantage don't indicate whether they have been GSA FIPS 201 approved.  I wonder if GSA can require the vendors on Schedule 70 and 84 to correct that.

**Comment by bob-fontana** [comment]
After a user drills down to look at the components (to get part numbers) on the APL, there is no way to get back to the previous location.  It is necessary to perform the search all over again.  Since the typical user will be moving back and forth on these screens, the inability for the web site to remember the user's previous state is annoying and wastes time.

**Comment by bob-fontana** [comment]
The GSA Advantage site has serious accuracy issues.  To the point that it is difficult to create a working example for the pacs-procure playbook.

**Comment by bob-fontana** [comment]
Need to review pacs-procure for over-use of acronyms.  How can we drop a few?

**Comment by bob-fontana** [comment]
GSA Advantaget web side should indicate that part numbers are part of a GSA FIPS 201 EP Approved Solution.

**Comment by bob-fontana** [comment]
This is a suggestion from Dan Myslewski to improve our guidance.  Rather than driving the agency Designated Officer to GSAAdvantage.com where they will get lost, we do the following:

1. Parse the APL for all manufacturers and their points of contact.
1. Craft an e-mail from Chi requesting from them, a list of their qualified installers/vars/integrators.  
1. Take that list and bounce it off the list of CSEIP-certified people
1. Take the results and publish it on idmanagement.gov, highlighting those SIs that have CSEIP-trained people.
1. Update the playbook to point agencies to that list.

**Comment by lachellel** [comment]
multiple issues in this thread. issue closed.
